name: relu
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  bloc: ^8.1.0
  connectivity_plus: ^2.3.6+1
  cupertino_icons: ^1.0.2
  equatable: ^2.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  http: ^0.13.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  lottie: ^1.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Light.ttf
        - asset: fonts/Nunito-Italic.ttf
          style: italic
        - asset: fonts/Nunito-Medium.ttf
        - asset: fonts/Nunito-MediumItalic.ttf
        - asset: fonts/Nunito-Regular.ttf
        - asset: fonts/Nunito-SemiBold.ttf
